---
language: python
python: "2.7"

env:
  - PHPENV_ENV=system
  - PHPENV_ENV=user

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git autoconf binutils-doc bison build-essential flex gettext ncurses-dev

install:
  - pip install ansible==1.8.4

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    -e "phpenv_env=$PHPENV_ENV"
    -e "phpenv_users=['travis']"
