---
- name: phpenv | Load the OS specific variables
  include_vars: "{{ansible_distribution | lower}}.yml"

- name: phpenv | Install php-build dependencies (Debian)
  apt: pkg={{ item }} state=present install_recommends=no
  with_items: build_dependencies
  sudo: true
